name: Generate Snake

on:
  schedule:
    - cron: "0 */6 * * *"   # every 6 hours
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3

      - name: Generate snake
        uses: Platane/snk@v3.4.0
        id: snake
        with:
          github_user_name: lamidu-rathnayake  # your GitHub username (exact, no spaces)
          svg_out_path: dist/github-contribution-grid-snake.svg
          gif_out_path: dist/github-contribution-grid-snake.gif
          svg_width: 1200          # bigger SVG width
          svg_height: 300          # bigger SVG height

      - name: Push to output branch
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
